mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from mysite.views import current_datetime, hours_ahead
from books import views

urlpatterns = [
	url(r'^time/$', current_datetime),
	url(r'^time/plus/(\d+)/$', hours_ahead),
	url(r'^admin/', admin.site.urls),
	url(r'^search-form/$', views.search_form),
	url(r'^search/$', views.search),
	url(r'^contact/$', views.contact),
]

books/models.py
from django.db import models

# Create your models here.
class Publisher(models.Model):
	name = models.CharField(max_length=30)
	address = models.CharField(max_length=50)
	city = models.CharField(max_length=60)
	state_province = models.CharField(max_length=30)
	country = models.CharField(max_length=50)
	website = models.URLField()

	def __unicode__(self):
		return self.name

	class Meta:
		ordering = ['name']

class Author(models.Model):
	salutation = models.CharField(max_length=10)
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=40)
	email  = models.EmailField(blank=True)
	headshot = models.ImageField(upload_to='tmp')

	def __unicode__(self):
		return u'%s %s' % (self.first_name, self.last_name)

class Book(models.Model):
	title = models.CharField(max_length=100)
	authors = models.ManyToManyField(Author)
	publisher = models.ForeignKey(Publisher)
	publication_date = models.DateField(blank=True, null=True)

	def __unicode__(self):
		return self.title

books/forms.py
from django import forms

class ContactForm(forms.Form):
	subject = forms.CharField(max_length=20)
	email = forms.EmailField(required=False,  label='Your e-mail address')
	message = forms.CharField(widget=forms.Textarea)
	
	def clean_message(self):
		message = self.cleaned_data['message']
		num_words = len(message.split())
		if num_words < 4:
			raise forms.ValidationError("Not enough words!")
		return message

books/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import render_to_response
from .models import Book
from .forms import ContactForm

# Create your views here.
def search_form(request):
	return render_to_response('search_form.html')

def search(request):
	errors = []
	if 'q' in request.GET:
		q = request.GET['q']
		if not q:
			errors.append('Enter a search term.')
		elif len(q) > 20:
			errors.append('Please enter at most 20 characters.')
		else:
			books = Book.objects.filter(title__icontains=q)
			return render_to_response('search_results.html', {'books': books, 'query': q})
	return render_to_response('search_form.html', {'errors': errors})

def contact(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			send_mail(
				cd['subject'],
				cd['message'],
				cd('email', 'noreply@example.com'),
				['siteowner@example.com'],
			)
			return httpResponseRedirect('/contact/thanks/')
	else:
		form = ContactForm(initial={'subject': 'I love your site!'})
	return render_to_response('contact_form.html', {'form': form})

mysite/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response
import datetime

def current_datetime(request):
	current_date = datetime.datetime.now()
	return render_to_response("current_datetime.html", locals())

def hours_ahead(request, offset):
	hour_offset = int(offset)
	next_time = datetime.datetime.now() + datetime.timedelta(hours=hour_offset)
	return render_to_response("future_time.html", locals())

mysite/templates/base.html
<!DOCTYPE html>!
<html lang="en">
<head>
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<h1>My helpful timestamp site</h1>
	{% block content %}{% endblock %}
	{% block footer %}
	<hr>
	<p>Thanks for visiting my site.</p>
	{% endblock %}
</body>
</html>

mysite/templates/contact_form.html
<html>
<head>
	<title>Contact us</title>
</head>
<body>
	<h1>Contact us</h1>
	
	{% if form.errors %}
		<p style="color: red;">
			Please correct the error{{ form.errors|pluralize }} below.
		</p>
	{% endif %}

	<form action="" method="post">
		<div class="field">
			{{ form.subject.errors }}
			<label for="id_subject">Subject:</label>
			{{ form.subject }}
		</div>
		<div class="field">
			{{ form.email.errors }}
			<label for="id_email">Email:</label>
			{{ form.email }}
		</div>
		<div class="field">
			{{ form.message.errors }}
			<label for="id_message">Message:</label>
			{{ form.message }}
		</div>
		<input type="submit" value="Submit">
	</form>
</body>
</html>

mysite/templates/current_datetime.html
{% extends "base.html" %}
{% block titile %}The current time{% endblock %}
{% block content%}
	<p>It is now {{ current_date }}.</p>
{% endblock %}

mysite/templates/future_time.html
{% extends "base.html" %}
{% block titile %}The Future time{% endblock %}
{% block content%}
	<p>In {{ hour_offset }} hour(s), it will be {{ next_time }}.</p>
{% endblock %}

mysite/templates/mytemplate.html
<html>
	<body>
		It's now {{ current_date }}.
	</body>
</html>

mysite/templates/search_form.html
<html>
<head>
	<title>Search</title>
</head>
<body>
	{% if errors %}
	<ul>
		{% for error in errors %}
		<li>{{ error }}</li>
		{% endfor %}
	</ul>
	{% endif %}
	<form action="/search/" method="get">
		<input type="text" name="q">
		<input type="submit" value="Search">
	</form>
</body>
</html>

mysite/templates/search_results.html
<p>You searched for: <string>{{ query }}</string></p>

{% if books %}
	<p>Found {{ books|length }} book{{ books|pluralize }}.</p>
	<ul>
		{% for book in books %}
		<li>{{ book.title }}</li>
		{% endfor %}
	</ul>
{% else %}
	<p>No books matched your search criteria.</p>
{% endif %}